server:
  port: 8091

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        opaque-token:
#          introspection-uri: http://localhost:9000
#          client-id: test
#          client-secret: test