server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: messaging-sms-client
          client-secret: secret3
          introspection-uri: http://localhost:9000/oauth2/introspect
#        jwt:
#          issuer-uri: http://localhost:9000

